################################################
# Server configurations
################################################
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080


################################################
# Application (global) configurations
################################################
application:
    # License path
    # Absolute path to GroupDocs license file
    licensePath: 'Licenses/GroupDocs.Signature.NET.lic'

################################################
# Common configurations
################################################
common:
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: true
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document download
  # Set false to disable document download
  download: true
  # Document upload
  # Set false to disable document upload
  upload: true
  # Document print
  # Set false to disable document print
  print: true
  # File browser
  # Set false to disable document browse
  browse: true
  # Set false to disable right mouse click
  enableRightClick: true

################################################
# GroupDocs.Signature configurations
################################################
signature:
  # Files directory path
  # Absolute path to files directory
  filesDirectory: 'DocumentSamples/Signature' 
  # Default document
  # Absolute or relative path to default document
  defaultDocument: ''
  # Pages preload
  # How many pages from a document should be loaded, remaining pages will be loaded on page scrolling
  # Set 0 to load all pages at once
  preloadPageCount: 0
  # Data directory path
  # Absolute path to signature cache files directory
  dataDirectory: ''
  # Enable/disable text signature
  textSignature: true
  # Enable/disable image signature
  imageSignature: true
  # Enable/disable digital signature
  digitalSignature: true
  # Enable/disable QR-Code signature
  qrCodeSignature: true
  # Enable/disable Barcode signature
  barCodeSignature: true
  # Enable/disable Stamp signature
  stampSignature: true
  # Enable/disable Hand signature
  handSignature: true
  # Enable/disable original document downloading
  downloadOriginal: true
  # Enable/disable signed document downloading
  downloadSigned: true
  # Enable/disable zoom
  zoom: true